### ISSUE TITLE
Tensor has to be on CPU before saving -- "Which way to synth1B1-312-6?"

### ISSUE THREAD

**Issue by daisukelab** [torchsynth/torchsynth#314]
Hi, I got this error.

```
torchaudio.save("synth1B1-312-6.wav", synth1B1_312_6.unsqueeze(0), voice.sample_rate)
--> RuntimeError: Input tensor has to be on CPU.
```
`synth1B1_312_6.cpu()` solves the issue, then you might want to change your example in a similar fashion.

**Comment by turian** [comment]
@daisukelab Thank you for your feedback, we have incorporated it. The documentation is now much richer and we are pinning version 1.0.0. We look forward to any feedback or thoughts you have. Best, Joseph
