### ISSUE TITLE
LFOs and modulation routing

### ISSUE THREAD

**Issue by maxsolomonhenry** [torchsynth/torchsynth#78]
Something to consider for the future. LFO's, and how they might be routed to one thing or another (pitch, filter cutoff).

One proposition is to have modulation routers/mixers internal to the Synth architecture.

So you'd have, say, a VCO that accepts a mod signal, but that signal has been previously mixed from a combination of envelope and lfo.

**Comment by turian** [comment]
@jorshi ?

**Comment by jorshi** [comment]
We've implemented a modulation mixer class in v1.0 :) https://torchsynth.readthedocs.io/en/latest/api/module.html#modulationmixer
